steps:
  - name: ':docker: Build and push Docker image to tink-containers'
    timeout_in_minutes: 10
    command: |
      # Build
      echo "$BUILDKITE_COMMIT"
      docker build -t xgboost:$BUILDKITE_COMMIT .

      # Tag and push image with version number to repository
      docker tag xgboost:$BUILDKITE_COMMIT gcr.io/tink-containers/xgboost:$BUILDKITE_COMMIT
      gcloud docker -- push gcr.io/tink-containers/xgboost:$BUILDKITE_COMMIT